name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: sacbase/sac-compiler
    steps:
      - uses: actions/checkout@v5
      - name: Configure sac2c
        run: mv /root/.sac2crc $HOME/.sac2crc
      - run: make all
      - run: ./test.sh
