name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: sacbase/sac-compiler
    steps:
      - uses: actions/checkout@v5
        path: home
      - run: ./test.sh
        working-directory: /home
