name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: sacbase/sac-compiler
    steps:
      - uses: actions/checkout@v5
      - run: |
          mv /root/.sac2crc $HOME/.sac2crc
          make all
          ./test.sh
