name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: sacbase/sac-compiler
      options: --user root
    steps:
      - uses: actions/checkout@v5
      - run: |
          ls
          echo $PWD
          sac2c -V
          ./test.sh
