name: main

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: sacbase/sac-compiler
    steps:
      - uses: actions/checkout@v5
      - run: echo "/root/.sac2crc" >> $GITHUB_PATH
      - run: |
          ls
          echo $PWD
          sac2c -V
          ./test.sh
